language: android
dist: trusty
android:
  components:
    - tools
    - platform-tools

    - build-tools-29.0.3

    - android-27
    - android-29

    # Additional components
    - extra-google-google_play_services
    - extra-android-m2repository
    - extra-android-support
    - extra-google-m2repository

    # Specify at least one system image,
    # if you need to run emulator(s) during your tests
    - sys-img-armeabi-v7a-android-27

  licenses:
    - 'android-sdk-preview-license-52d11cd2'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'

before_install:
  - yes | sdkmanager "platforms;android-29"
  - yes | sdkmanager "build-tools;29.0.3"
  - mkdir -p "$ANDROID_HOME/licenses"
  - echo -e "\n8933bad161af4178b1185d1a37fbf41ea5269c55" > "$ANDROID_HOME/licenses/android-sdk-license"
  - echo -e "\n84831b9409646a918e30573bab4c9c91346d8abd" > "$ANDROID_HOME/licenses/android-sdk-preview-license"
  - chmod +x gradlew
  - ./gradlew dependencies || true

# Emulator Management: Create, Start and Wait
before_script:
  - echo no | android create avd --force -n test -t android-27 --abi armeabi-v7a
  - QEMU_AUDIO_DRV=none emulator -avd test -no-window &
  - android-wait-for-emulator
  - adb shell input keyevent 82 &

script:
  - ./gradlew clean build connectedCheck